name: Cleanup XenAPI environment
description: Cleanup XenAPI environment created using the setup-xapi-environment composite action

runs:
  using: "composite"
  steps:
    - name: Uninstall unversioned packages and remove pins
      shell: bash
      # This should purge them from the cache, unversioned package have
      # 'master' as its version
      run: |
        opam list | awk -F " " '$2 == "master" { print $1 }' |  xargs opam uninstall
        opam pin list | cut -f1 -d "." | xargs opam unpin
